"use client";

import "./globals.css";
import { FavoriteProvider, useFavorites } from "@/context/context";
import { Card, CardsContainer, Navbar } from "@/components";
import { Inter } from "next/font/google";
import Image from "next/image";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Props {
	children: React.ReactNode;
}

function RootLayout({ children }: Props) {
	const [favorites] = useFavorites();

	return (
		<html lang="en">
			<body
				className={`${inter.className} sm:max-w-screen-sm md:max-w-screen-md lg:max-w-screen-lg mx-auto py-4`}
			>
				<Navbar />
				{children}
				<hr />
				<section className="mt-4">
					{favorites.length > 0 ? (
						<section className="grid gap-2 grid-cols-container">
							<CardsContainer data={favorites} />
						</section>
					) : (
						<span>No favorites</span>
					)}
				</section>
			</body>
		</html>
	);
}

export default function RootLayoutContainer(props: Props) {
	return (
		<FavoriteProvider>
			<RootLayout {...props} />
		</FavoriteProvider>
	);
}
